### ISSUE TITLE
does the backbone the do detection and segmentation task simuteneously well?

### ISSUE THREAD

**Issue by jinfagang** [Visual-Attention-Network/SegNeXt#1]
does the backbone the do detection and segmentation task simuteneously well?

**Comment by MenghaoGuo** [comment]
Yes. 

I am sure it can work well on detection benchmark.  

It is worth noting that you need to adjust the droppath （>= 0.3） when training a base (or larger) model. 

So sorry about it. We do not organize and release detection related code recently, due to various ddl.

if you are interested in detection, You can send me an email (gmh20@mails.tsinghua.edu.cn) and I will give an unorganized code based on mmdetection. 

Thank you for your interest in our work.

Best,

Menghao

**Comment by jinfagang** [comment]
@MenghaoGuo for sure. I have sent an email. BTW, did u guys have an AP comparsion on some sota models? I'd like to integrate VAN into detectron2 and combine it with YOLO arch.
