### ISSUE TITLE
Is it possible to export SegNeXt as ONNX or tensorrt model to speedup inferencing?

### ISSUE THREAD

**Issue by chenxinfeng4** [Visual-Attention-Network/SegNeXt#25]
The SegNeXt is a great job to use multiscale/large convolution kernel to mimic the "attention". I was wondering if it's possible to export your model to the ONNX or the tensorrt? The tensorrt will speed up 2x to 10x than original pytorch, that will be very helpful for us in video prediction.

Your model is based on mmsegmentation which already allows model deployment. I see your code, but wonder some operation may not be supported by ONNX or tensorrt, such as 'unsqueeze' / 'flatten'.

Bests

**Comment by MenghaoGuo** [comment]
Great idea.

Converting SegNeXt into ONNX to speed up it is a good idea. However, we do not do it due to all kind of DDL.  Thus, we do not know what will happen in the process

If you are interested in it, you can have a try. We are willing to provide help. You can keep this issue until the conversion is successful.

Best, 
Menghao

**Comment by akuxcw** [comment]
Hi, I'm sorry to re-open this issue. Have you successfully deployed SegNeXt to tensorrt model?
